export default {
  home: require('../assets/home.png'),
  Add: require('../assets/add.png'),
  banner2: require('../assets/banner2.jpg'),
  banner3: require('../assets/banner3.jpg'),
  banner4: require('../assets/banner4.jpg'),
  banner5: require('../assets/banner5.jpg'),
  banner1: require('../assets/banner2.jpg'),
  p1: require('../assets/p1.png'),
  p2: require('../assets/p2.png'),
  p3: require('../assets/p3.png'),
  p4: require('../assets/p4.png'),
  heart: require('../assets/heart.png'),
  heartOutline: require('../assets/heart-outline.png'),
  testing: require('../assets/testing.png'),
  // bell: require('../assets/bell.png'),
  blogging: require('../assets/blogging.png'),
  book: require('../assets/book.png'),
  dollar: require('../assets/dollar.png'),
  drone: require('../assets/drone.png'),
  group: require('../assets/group.png'),
  plant: require('../assets/plant.png'),
  search: require('../assets/search.png'),
  settings: require('../assets/settings.png'),
  sms: require('../assets/sms.png'),
  video: require('../assets/video.png'),
  weather: require('../assets/weather.png'),
  cart: require('../assets/cart.png'),
  news: require('../assets/news.png'),
  support: require('../assets/support.png'),
  wishlist: require('../assets/wishlist.png'),
  farmerCall: require('../assets/farmerCall.jpg'),
  Admin: require('../assets/profile.png'),
  faq: require('../assets/question.png'),
  forwardArrow: require('../assets/forwardArrow.png'),
  delete: require('../assets/bin.png'),
  edit: require('../assets/edit.png'),
};
