export default {
  TabHome: 'TabHome',
  Chat: 'Chat',
  Shop: 'Shop',
  Furtilizer: 'Furtilizer',
  Setting: 'Setting',
  GiftedChat: 'GiftedChat',
  FAQ: 'FAQ',
  MarketPrice: 'MarketPrice',
  Videos: 'Videos',
  SoilTesting: 'SoilTesting',
  CropPractices: 'CropPractices',
  CropDetail: 'CropDetail',
  AddCrop: 'AddCrop',
  AddProduct: 'AddProduct',
  AddPrice: 'AddPrice',
  AllProducts: 'AllProducts',
  AllCrops: 'AllCrops',
  AllPrices: 'AllPrices',
  SaleHistory: 'SaleHistory',
  PurchaseHistory: 'PurchaseHistory',
  Cart: 'Cart',
};
